import { fileURLToPath } from 'node:url';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { Db } from './client.ts';

/** apps/server/drizzle, generated by `pnpm db:generate` from src/db/schema.ts. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

/** Arbitrary constant for pg_advisory_lock, so two processes never migrate at the same time. */
const MIGRATION_LOCK_ID = 7_340_201;

/**
 * Applies pending migrations. Drizzle records applied migrations in drizzle.__drizzle_migrations
 * and runs them in one transaction, but takes no lock; the advisory lock makes it safe when the
 * API start and `pnpm db:migrate` overlap.
 */
export async function runMigrations(db: Db): Promise<void> {
  const lockClient = await db.$client.connect();
  try {
    await lockClient.query('select pg_advisory_lock($1)', [MIGRATION_LOCK_ID]);
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await lockClient.query('select pg_advisory_unlock($1)', [MIGRATION_LOCK_ID]).catch(() => undefined);
    lockClient.release();
  }
}
